// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZ034D3Zs22SpvFnc7yMKgpA7Mhpp5G4',
    appId: '1:739437044691:android:325870ea7d4f6f01690526',
    messagingSenderId: '739437044691',
    projectId: 'flutter-project1-1739f',
    databaseURL: 'https://flutter-project1-1739f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project1-1739f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5-_gIN_WP7e4F_EJ9es6tzQRIVYuEb4',
    appId: '1:739437044691:ios:6a64b994ecc913e7690526',
    messagingSenderId: '739437044691',
    projectId: 'flutter-project1-1739f',
    databaseURL: 'https://flutter-project1-1739f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project1-1739f.appspot.com',
    iosClientId: '739437044691-dhb3uap7046q9tqfj2og191acjpapgvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrition',
  );
}
